Repository googleapis/nodejs-cloud-container, pull requests merged in 2019-05, with the labels that each got.

#182 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#183 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#184 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#187 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#188 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: automerge, cla: yes

#186 build: only pipe to codecov if tests run in Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#189 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#190 fix: DEADLINE_EXCEEDED is no longer retried
  src/v1/cluster_manager_client_config.json
  synth.metadata
Labels: cla: yes

#192 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1/cluster_manager_client_config.json
  synth.metadata
Labels: cla: yes

#193 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#195 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#196 refactor: use repo-metadata to generate readme
  .cloud-repo-tools.json
  .gitignore
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  samples/quickstart.js
  src/v1/cluster_manager_client.js
  synth.metadata
Labels: cla: yes

#197 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#198 chore: drop dependency on lodash.merge
  package.json
Labels: cla: yes

#199 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#200 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#201 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
