Repository googleapis/nodejs-cloud-container, pull requests merged in 2020-12, with the labels that each got.

#405 chore: generate GAPIC metadata JSON file
  src/v1/gapic_metadata.json
  synth.metadata
Labels: cla: yes, context: full

#407 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#408 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
