Repository googleapis/nodejs-cloud-container, pull requests merged in 2020-11, with the labels that each got.

#396 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#397 build: add type for ClusterManagerClient
  src/index.ts
  synth.metadata
Labels: cla: yes, context: none

#398 fix: do not modify options object, use defaultScopes
  package.json
  src/v1/cluster_manager_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: automerge, cla: yes

#401 feat: update GKE v1 API
  package.json
  protos/google/container/v1/cluster_service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/cluster_manager_client.ts
  src/v1/cluster_manager_client_config.json
  synth.metadata
  test/gapic_cluster_manager_v1.ts
Labels: cla: yes

#403 fix(browser): check for fetch on window
  src/v1/cluster_manager_client.ts
  synth.metadata
Labels: cla: yes, context: full

#404 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
