Repository googleapis/nodejs-cloud-container, pull requests merged in 2020-05, with the labels that each got.

#340 fix: regen protos and tests
  protos/protos.js
  synth.metadata
  test/gapic_cluster_manager_v1.ts
Labels: automerge, cla: yes

#341 fix: synth.py clean up for multiple version
  protos/protos.js
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#342 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
